### ISSUE TITLE
.browserslistrc

### ISSUE THREAD

**Issue by aerni** [scottcharlesworth/laravel-mix-polyfill#5]
Does this also work with a `.browserslistrc` file instead of defining the targets directly in the `webpack.mix.js` config?

**Comment by scottcharlesworth** [comment]
@aerni90 no it doesn't. I think it's because Laravel Mix is a _wrapper_ around Webpack. So the `.browserslistrc` file at the root of your project cannot be seen when compiling. I tried a few different methods to get this to work.

If you are desperate, you could read the contents of the `.browserslistrc` to an array and then pass it to targets. Something like:

```js
const mix = require('laravel-mix');
const fs = require('fs');

require('laravel-mix-polyfill');
 
let contents = fs.readFileSync('.browserslistrc', 'utf8').toString().split("\n");

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .polyfill({enabled: true, targets: contents});
```

Hope that helps!

**Comment by scottcharlesworth** [comment]
@aerni90 if you set the `targets` option to `false` that will allow use of a `.browserslistrc` file.

```js
const mix = require('laravel-mix');
require('laravel-mix-polyfill');

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .polyfill({targets: false});
```

I've updated the documentation to better explain this.
